In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../feature engineering/DATA/Advertising.csv")

In [3]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop('sales', axis=1)

In [5]:
y = df['sales']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(X_train)

StandardScaler()

In [11]:
X_train = scaler.transform(X_train)

In [12]:
X_test = scaler.transform(X_test)

In [13]:
from sklearn.linear_model import ElasticNet

In [14]:
base_elastic_net_model = ElasticNet()

In [26]:
param_grid = {'alpha':np.arange(0.05, 0.2, 0.02), 
              'l1_ratio':[0.1, 0.2, 0.5, 0.7, 0.99, 0.9, 0.85, 1]}

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
grid_model = GridSearchCV(estimator=base_elastic_net_model, 
                          param_grid=param_grid, 
                          scoring='neg_mean_squared_error', 
                          cv=5,
                          verbose=2)

In [29]:
grid_model.fit(X_train, y_train)

Fitting 5 folds for each of 64 candidates, totalling 320 fits
[CV] END ...........................alpha=0.05, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.7; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.05, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.05, l1_ratio=0.85; total time=   0.0s
[CV] END .............................alpha=0.05, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.05, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.05, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.05, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.05, l1_ratio=1; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.7; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.07, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.07, l1_ratio=0.85; total time=   0.0s
[CV] END .............................alpha=0.07, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.07, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.07, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.07, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.07, l1_ratio=1; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.09000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.09000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ..............alpha=0.09000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.09000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.09000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.09000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.09000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.7; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.99; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.11000000000000001, l1_ratio=0.9; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.11000000000000001, l1_ratio=0.85; total time=   0.0s
[CV] END ..............alpha=0.11000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.11000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.11000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.11000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.11000000000000001, l1_ratio=1; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.2; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.5; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.7; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.7; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.99; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.99; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.13, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.85; total time=   0.0s
[CV] END ..........................alpha=0.13, l1_ratio=0.85; total time=   0.0s
[CV] END .............................alpha=0.13, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.13, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.13, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.13, l1_ratio=1; total time=   0.0s
[CV] END .............................alpha=0.13, l1_ratio=1; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.2; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.5; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.7; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.7; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.99; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.99; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.9; total time=   0.0s
[CV] END ............alpha=0.15000000000000002, l1_ratio=0.9; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.85; total time=   0.0s
[CV] END ...........alpha=0.15000000000000002, l1_ratio=0.85; total time=   0.0s
[CV] END ..............alpha=0.15000000000000002, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.15000000000000002, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.15000000000000002, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.15000000000000002, l1_ratio=1; total time=   0.0s
[CV] END ..............alpha=0.15000000000000002, l1_ratio=1; total time=   0.0s
[CV] END ............alpha=0.17000000000000004, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.17000000000000004, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.17000000000000004, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.17000000000000004, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.17000000000000004, l1_ratio=0.1; total time=   0.0s
[CV] END ............alpha=0.17000000000000004, l1_ratio=0.2; total time=   0.0s

GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': array([0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.17, 0.19]),
                         'l1_ratio': [0.1, 0.2, 0.5, 0.7, 0.99, 0.9, 0.85, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [30]:
grid_model.best_estimator_

ElasticNet(alpha=np.float64(0.07), l1_ratio=1)

In [36]:
df_res = pd.DataFrame(grid_model.cv_results_)

In [38]:
df_res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001566,0.000546,0.000676,0.000095,0.05,0.10,"{'alpha': 0.05, 'l1_ratio': 0.1}",-4.238012,-2.051322,-2.332035,-2.496248,-4.135410,-3.050606,0.939038,37
1,0.001277,0.000100,0.000733,0.000159,0.05,0.20,"{'alpha': 0.05, 'l1_ratio': 0.2}",-4.230882,-2.036975,-2.318809,-2.484318,-4.132902,-3.040777,0.943143,35
2,0.001467,0.000155,0.000818,0.000163,0.05,0.50,"{'alpha': 0.05, 'l1_ratio': 0.5}",-4.212369,-1.997982,-2.274261,-2.450362,-4.127488,-3.012492,0.956360,26
3,0.001909,0.000442,0.001036,0.000138,0.05,0.70,"{'alpha': 0.05, 'l1_ratio': 0.7}",-4.202606,-1.975723,-2.245133,-2.429371,-4.125743,-2.995715,0.965200,19
4,0.001406,0.000231,0.000739,0.000207,0.05,0.99,"{'alpha': 0.05, 'l1_ratio': 0.99}",-4.192487,-1.949507,-2.205783,-2.401495,-4.126070,-2.975068,0.977699,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,0.001065,0.000106,0.000513,0.000045,0.19,0.70,"{'alpha': 0.19, 'l1_ratio': 0.7}",-4.064539,-2.167443,-2.674837,-2.773436,-4.137758,-3.163603,0.792984,51
60,0.000965,0.000046,0.000516,0.000047,0.19,0.99,"{'alpha': 0.19, 'l1_ratio': 0.99}",-3.949091,-2.027357,-2.454217,-2.607481,-4.082512,-3.024132,0.832788,30
61,0.000983,0.000113,0.000493,0.000025,0.19,0.90,"{'alpha': 0.19, 'l1_ratio': 0.9}",-3.979168,-2.063409,-2.519197,-2.654589,-4.096088,-3.062490,0.820772,40
62,0.000907,0.000024,0.000494,0.000042,0.19,0.85,"{'alpha': 0.19, 'l1_ratio': 0.85}",-3.998280,-2.085212,-2.556753,-2.682553,-4.105095,-3.085579,0.814280,43
63,0.000962,0.000075,0.000485,0.000011,0.19,1.00,"{'alpha': 0.19, 'l1_ratio': 1}",-3.946120,-2.023621,-2.447221,-2.602520,-4.081224,-3.020141,0.834150,28

In [40]:
df_res.sort_values(by='mean_test_score', ascending=False)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
15,0.001177,0.000040,0.000636,0.000080,0.07,1.00,"{'alpha': 0.07, 'l1_ratio': 1}",-4.151196,-1.951195,-2.233926,-2.420115,-4.088785,-2.969043,0.951740,1
12,0.001601,0.000239,0.000935,0.000114,0.07,0.99,"{'alpha': 0.07, 'l1_ratio': 0.99}",-4.151669,-1.952293,-2.235852,-2.421495,-4.088837,-2.970029,0.951178,2
23,0.001016,0.000093,0.000490,0.000019,0.09,1.00,"{'alpha': 0.09000000000000001, 'l1_ratio': 1}",-4.112121,-1.959118,-2.265107,-2.444151,-4.074020,-2.970904,0.929362,3
20,0.001391,0.000276,0.000775,0.000209,0.09,0.99,"{'alpha': 0.09000000000000001, 'l1_ratio': 0.99}",-4.112870,-1.960162,-2.267732,-2.445733,-4.074059,-2.972111,0.928750,4
7,0.000977,0.000104,0.000490,0.000015,0.05,1.00,"{'alpha': 0.05, 'l1_ratio': 1}",-4.192228,-1.948743,-2.204491,-2.400599,-4.126145,-2.974441,0.978121,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,0.001180,0.000578,0.000627,0.000309,0.15,0.10,"{'alpha': 0.15000000000000002, 'l1_ratio': 0.1}",-4.326659,-2.452034,-2.889905,-2.957129,-4.202670,-3.365680,0.755256,60
49,0.000896,0.000009,0.000473,0.000004,0.17,0.20,"{'alpha': 0.17000000000000004, 'l1_ratio': 0.2}",-4.314111,-2.474472,-2.951320,-3.008529,-4.228326,-3.395352,0.739294,61
48,0.000989,0.000087,0.000484,0.000013,0.17,0.10,"{'alpha': 0.17000000000000004, 'l1_ratio': 0.1}",-4.370331,-2.554259,-3.023281,-3.071964,-4.240688,-3.452105,0.721045,62
57,0.001063,0.000094,0.000523,0.000033,0.19,0.20,"{'alpha': 0.19, 'l1_ratio': 0.2}",-4.354263,-2.569636,-3.078851,-3.119381,-4.266632,-3.477752,0.707507,63
56,0.001048,0.000112,0.000530,0.000049,0.19,0.10,"{'alpha': 0.19, 'l1_ratio': 0.1}",-4.420715,-2.661770,-3.161945,-3.192512,-4.285486,-3.544486,0.687934,64

In [41]:
y_pred = grid_model.predict(X_test)

In [42]:
from sklearn.metrics import mean_squared_error

In [43]:
mean_squared_error(y_test, y_pred)

2.9222612825253944